FROM node:alpine

WORKDIR /usr/app

# RUN npm install --global yarn

COPY package.json .

# RUN npm install --legacy-peer-deps

RUN npm install gatsby-plugin-image --legacy-peer-deps

CMD ["npm", "run", "develop"]