version: '3'
services:
  webfolio:
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - "8100:8100"
    volumes:
      - /usr/app/node_modules
      - .:/usr/app
  # test:
  #   build:
  #     context: .
  #     dockerfile: Dockerfile.dev
  #   volumes:
  #     - /usr/app/node_modules
  #     - .:/usr/app
  #   command: ["npm", "run", "test"]